title: National Crime Prevention Council
url: https://www.scamshield.org.sg
favicon: /images/scamshield-favicon.png
colors:
  primary-color: "#001E6C"
  secondary-color: "#2D81FF"
  media-colors:
    - title: media-color-one
      color: "#d0021b"
    - title: media-color-two
      color: "#f5a623"
    - title: media-color-three
      color: "#f8e71c"
    - title: media-color-four
      color: "#bd10e0"
    - title: media-color-five
      color: "#00838f"
is_government: false
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
description: ""
resources_name: ""
staging: https://scamshield-staging.netlify.app/
prod: https://scamshield-prod.netlify.app/
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
shareicon: /images/isomer-logo.svg
facebook-pixel: ""
google_analytics: UA-240633659-1
linkedin-insights: ""
